gitlab-users-cleanup: Update to use latest API
Otherwise, get this error when using python3-gitlab 1:3.5.0-1:

    Traceback (most recent call last):
      File "/home/user/proj/tails/tails/./bin/gitlab-users-cleanup", line 256, in <module>
        group_members_ids = [m.id for m in group.members.all(all=True)]
    AttributeError: 'GroupMemberManager' object has no attribute 'all'

refs tails#19068