Test suite: fix reporting of hostname leaks via DHCP
This problem can't be reproduced on Tails 4.x, which does not leak
the hostname. But on feature/bullseye we see this:

  undefined local variable or method `hostname' for #<Object:0x00005623d262c9a0> (NameError)

Fixes regression I introduced in 4e45a449c3b2c16a8ce61c8e12afc2373b2e5e28.