Revert "Dogtail: ensure showingOnly is set by default."
This reverts commit fcee8606e9bef535153dbe10a0655fde7bec7582.

Since that commit was introduced, I see lots of:

    The Dogtail script raised: TypeError: __init__() got an unexpected keyword argument 'showingOnly' (Dogtail::Failure)
    ./features/support/helpers/dogtail.rb:99:in `run'
    ./features/support/helpers/dogtail.rb:194:in `children'